version: '3.3'

services:
  db:
    image: mariadb
    restart: always
    hostname: saruman-db
    container_name: saruman-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: saruman
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  api:
    restart: always
    container_name: saruman-api
    hostname: saruman-api
    depends_on:
      - "db"
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/docker-mnt/saruman/api
    environment:
      - MYSQL_CONN_STRING=${MYSQL_CONN_STRING}
      - PATH=/conf/bin:${PATH}

  adminer:
    image: adminer
    restart: always
    container_name: saruman-adminer
    hostname: saruman-adminer
    depends_on:
      - "db"
    ports:
      - "3001:8080"
