version: '3.8'

services:
  db:
    image: mariadb
    hostname: saruman-db
    container_name: saruman-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSOWRD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: saruman
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  web:
    container_name: saruman-api
    hostname: saruman-api
    depends_on:
      - "db"
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/docker-mnt/saruman/api
    environment:
      - MY_SQL_CONN_STRING=${MY_SQL_GORM_CONN_STRING}
      - PATH=/conf/bin:${PATH}

  adminer:
    image: adminer
    container_name: saruman-adminer
    hostname: saruman-adminer
    depends_on:
      - "db"
    restart: always
    ports:
      - "3001:8080"
