version: '3.3'

services:
  db:
    image: mariadb
    restart: always
    hostname: saruman-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: saruman
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  api:
    image: xburrow/saruman:latest-prod
    restart: always
    hostname: saruman-api
    depends_on:
      - "db"
    ports:
      - "3000"
    volumes:
      - /docker-mnt/saruman-api:/go/saruman/src
    environment:
      - MYSQL_CONN_STRING=${MYSQL_CONN_STRING}

  adminer:
    image: adminer
    restart: always
    hostname: saruman-adminer
    depends_on:
      - "db"
    ports:
      - "3001:8080"
